### ISSUE TITLE
添加设置设备信息的选项

### ISSUE THREAD

**Issue by 250king** [Rsplwe/ESurfingDialer#10]
我的学校仅允许一台电脑和一个手机上线，我希望借此在路由器实现多拨，但要两者设备信息不一样

**Comment by Rsplwe** [comment]
确定是设备信息的问题吗？程序运行时标识设备的只有设备名称是固定的，其他皆为运行时随机生成。

**Comment by 250king** [comment]
我今天特意抓了Windows端的数据包，发现其UA是不一样的
<img width="583" alt="image" src="https://github.com/Rsplwe/ESurfingDialer/assets/61256966/525250fc-1940-4f7c-be6c-91809441870a">
不过后来在虚机（设置桥接模式）和主机一起登录测试，的确可以照常使用，没有问题了
![image](https://github.com/Rsplwe/ESurfingDialer/assets/61256966/9ea45e3d-b3e8-4b16-96fb-8fd386a18782)
但我准备在OpenWrt启用多拨，会涉及到多个网卡，能不能指定网卡进行登录认证

**Comment by Rsplwe** [comment]
> 能不能指定网卡进行登录认证
JVM 不支持绑定 Socket 到网络设备

**Comment by 250king** [comment]
那怎么用libcurl？
其实在进行登录之前可以先把mwan3给关掉，然后再进行登录，登录完了再重启

**Comment by Rsplwe** [comment]
> 那怎么用libcurl？ 

需要对网络请求部分进行重写

> 其实在进行登录之前可以先把mwan3给关掉，然后再进行登录，登录完了再重启

但后续的网络请求还是会被分流

**Comment by 250king** [comment]
难不成只能在mwan指定相应的出口分流，然后再登录？
但学校这边每48小时后会强制性退出一次，那可以通过某些脚本重新设置分流吗？
如果说可以做到这一点，那没必要指定网卡，直接通过上述方法

**Comment by 250king** [comment]
其实还有一个思路，那就是Java只负责用来解密和加密，网络请求的部分通过命令行调用curl，curl是可以指定网卡的
就唯一的缺点是必须安装curl
这算是最简单粗暴的方法了

**Comment by Rsplwe** [comment]
> 其实还有一个思路，那就是Java只负责用来解密和加密，网络请求的部分通过命令行调用curl，curl是可以指定网卡的 就唯一的缺点是必须安装curl 这算是最简单粗暴的方法了

可以提交PR

**Comment by 250king** [comment]
可以给个请求的范例吗？我好设计Curl指令（就只需要getTicket那一部分）

**Comment by Rsplwe** [comment]
> 可以给个请求的范例吗？我好设计Curl指令（就只需要getTicket那一部分）

都在源码里

**Comment by 250king** [comment]
不知道有没有可行性
https://www.baeldung.com/java-network-interfaces
https://stackoverflow.com/questions/36197002/how-can-i-specify-which-network-interface-okhttp-will-use-when-establishing-new

**Comment by 250king** [comment]
很不幸，从去年12月开始，疑似系统升级修复了bug，已经不允许同时两个手机端同时在线，否则会同时断网。
所以还是要弄客户端类型伪装

**Comment by 250king** [comment]
近期听到有人反馈，用同一个脚本，但在不同的系统运行不会造成下线。我后来开了台Windows和Debian一起实验并经过8分钟的long ping的确没有掉线的情况。那也就意味着校园网有可能是根据网络特指（TTL，NetBIOS，DHCP Identifier）来判断客户端
