### ISSUE TITLE
疑似有内存泄漏，且过一段时间不会发包导致断网

### ISSUE THREAD

**Issue by 250king** [Rsplwe/ESurfingDialer#19]
我已经在OpenWrt设置好了Java环境，设置了512M内存，应用也运行成功了，此时（11:46）我也关注了一下内存占用，大概才160M多。
![image](https://github.com/Rsplwe/ESurfingDialer/assets/61256966/cfaaa486-de1c-4911-8cae-dbf1ba004938)
但后来过了9小时后（20:46）收到舍友报障说断网了，然后我查看了一下，发现内存快爆了，然后我设置了日志输出流显示18:41发完包后不会继续下去了，而且还不会报错
![image](https://github.com/Rsplwe/ESurfingDialer/assets/61256966/3a9ea66b-ed38-43d5-8987-5d5459784c10)
![image](https://github.com/Rsplwe/ESurfingDialer/assets/61256966/a16c464b-fdae-4360-934f-b2bf253242e8)

**Comment by Rsplwe** [comment]
fixed https://github.com/Rsplwe/ESurfingDialer/commit/19f3c9aea7be8d8a6fa0a9de9a7f290cf1952d4a
