### ISSUE TITLE
[Feat] ghcr  Docker 镜像支持

### ISSUE THREAD

**Issue by SummonHIM** [Rsplwe/ESurfingDialer#21]
[Github Package](https://github.com/users/Rsplwe/packages?repo_name=ESurfingDialer) 能储存编译后的 Docker 镜像到`ghcr.io/<用户名>/<仓库名>`。
大佬可参阅一下官方的 [Workflow 范例](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml)
希望能简化一下 Docker 部署流程。

_缺点是一堵墙导致速度没有docker hub那么快_

**Comment by twobottlewater** [comment]
怎么使用啊楼主,能不能写写详细点呜呜呜

**Comment by Rsplwe** [comment]
> 希望能简化一下 Docker 部署流程。

目前来说已经足够了，提供预配置容器反而降低了自定义配置的灵活性

**Comment by SummonHIM** [comment]
> > 希望能简化一下 Docker 部署流程。
> 
> 目前来说已经足够了，提供预配置容器反而降低了自定义配置的灵活性

通过环境变量传入自定义配置？

**Comment by xiaoyangdkj** [comment]
> 怎么使用啊楼主,能不能写写详细点呜呜呜

介绍已经很简洁了，下载java21，进该Releases下载jar文件，进cmd或者powershell运行jar文件（附带参数）就行了...

Docker部署这里我有点看不懂，直到看到run.sh才反应过来是文件名...还是老样子，新建Dockerfile、run.sh填入内容，然后把Releases里的jar文件改名client.jar，最后把两个运行文件(.sh/.jar)都无脑chmod +x就可以抓去docker build和docker run了

**Comment by twobottlewater** [comment]
@xiaoyangdkj ,感谢,我前天就摸索会用了,我在教了其他人,让知识传播下去

**Comment by SummonHIM** [comment]
不用docker都可以了，只要DHCP下随便一台机器都能登录。登录一下DHCP范围内都有网。是我想的太复杂了
