### ISSUE TITLE
大佬求解决

### ISSUE THREAD

**Issue by lingcj** [Rsplwe/ESurfingDialer#27]
经常性的使用了几小时后突然断网，重新运行脚本显示如图，此时打开原软件天翼校园显示已联网但实际无法连接，过一会后浏览器弹出验证页面时重新运行脚本才能成功
![Image_1713960368797](https://github.com/Rsplwe/ESurfingDialer/assets/167860492/123b8764-eb7d-4603-9e8f-2e3ceed79646)

**Comment by Rsplwe** [comment]
请提供下发生这种情况时的完整日志、当前网络连接状态的详细信息，以及 `nslookup 189.cn` 的执行结果

**Comment by lingcj** [comment]
![屏幕截图 2024-04-25 214034](https://github.com/Rsplwe/ESurfingDialer/assets/167860492/b505fdaa-a816-4647-a898-3e9a688e2a66)
![屏幕截图 2024-04-25 214126](https://github.com/Rsplwe/ESurfingDialer/assets/167860492/9d16fc9a-2d4f-49d3-a3ef-d659c812fa08)
![屏幕截图 2024-04-25 214225](https://github.com/Rsplwe/ESurfingDialer/assets/167860492/9daa5ee4-697f-4e48-a678-257bb4fef7ea)
用了一小时多后开始坦error，此时有网络。保持原状两小时后突然断网，指令执行效果如图，过大概五分钟后浏览器弹出弹窗，此时脚本自动重连，恢复有网

**Comment by Rsplwe** [comment]
我大概知道原因了，www.gstatic.com 被解析到国外的谷歌云节点，等下一个版本修复

**Comment by 250king** [comment]
建议改为国内的检查站，比如小米的http://connect.rom.miui.com/generate_204 ，华为的http://connectivitycheck.platform.hicloud.com/generate_204等

**Comment by Rsplwe** [comment]
fixed
