### ISSUE TITLE
大佬这个是怎么回事

### ISSUE THREAD

**Issue by wulafish** [Rsplwe/ESurfingDialer#28]
关闭客户端后运行就这样了
![8c1f973108b97777b3f95ff3cfa29df](https://github.com/Rsplwe/ESurfingDialer/assets/85572423/341838a9-c247-4eb9-afbf-a860d7e6917b)

**Comment by ldy2333** [comment]
遇到同样情况，通过手机登录天翼校园检查，发现答案是账号欠费（捂脸

**Comment by ldy2333** [comment]
遇到同样情况，通过手机登录天翼校园检查，发现答案是账号欠费🤡
