### ISSUE TITLE
使用n1盒子的openwrt运行，运行不了。

### ISSUE THREAD

**Issue by wang8456** [Rsplwe/ESurfingDialer#30]
![image](https://github.com/Rsplwe/ESurfingDialer/assets/113652726/8eb59961-aca6-4da3-8cca-1c879df5af7e)
大佬wo我使用op运行它弹出这个。

**Comment by wang8456** [comment]
![image](https://github.com/Rsplwe/ESurfingDialer/assets/113652726/9ef16c1a-2d71-42b4-900d-a6597bbc6c77)

**Comment by wang8456** [comment]
![image](https://github.com/Rsplwe/ESurfingDialer/assets/113652726/70171d0d-3469-4bac-a601-191850ec1a98)
给run.sh权限，然后构建镜像之后打开显示这个。

**Comment by wang8456** [comment]
我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。

**Comment by xiaoyangdkj** [comment]
> 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。

run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限

**Comment by wang8456** [comment]
run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。

**Comment by wang8456** [comment]
> > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> 
> run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......

run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。

**Comment by xiaoyangdkj** [comment]
> > > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> > 
> > run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......
> 
> run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。

docker pull xiaoyangdkj/esurfingdialer:v1.4.0
em...要不试试这个？

**Comment by wang8456** [comment]
> > > > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > > > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> > > 
> > > 
> > > run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......
> > 
> > 
> > run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。
> 
> 我好像知道怎么回事了，你是不是忘记给jar文件重命名了（run.sh里面有写）

也应该不是，我重命名成client.jar了。

**Comment by xiaoyangdkj** [comment]
> > > > > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > > > > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> > > > 
> > > > 
> > > > run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......
> > > 
> > > 
> > > run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。
> > 
> > 我好像知道怎么回事了，你是不是忘记给jar文件重命名了（run.sh里面有写）
> 
> 也应该不是，我重命名成client.jar了。

我两个月前打包过一个镜像，或许你可以去dockerhub看看...

**Comment by wang8456** [comment]
> > > > > > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > > > > > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> > > > > 
> > > > > 
> > > > > run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......
> > > > 
> > > > 
> > > > run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。
> > > 
> > > 
> > > 我好像知道怎么回事了，你是不是忘记给jar文件重命名了（run.sh里面有写）
> > 
> > 
> > 也应该不是，我重命名成client.jar了。
> 
> 我两个月前打包过一个镜像，或许你可以去dockerhub看看... docker pull xiaoyangdkj/esurfingdialer:v1.4.0

老哥创建容器的时候要写哪些参数，照着这个库里的 
这个运行吗？
docker run -itd -e DIALER_USER=<用户名/手机号> -e DIALER_PASSWORD=<密码> --name dialer-client --network host --restart=always dialer

**Comment by xiaoyangdkj** [comment]
> > > > > > > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > > > > > > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> > > > > > 
> > > > > > 
> > > > > > run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......
> > > > > 
> > > > > 
> > > > > run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。
> > > > 
> > > > 
> > > > 我好像知道怎么回事了，你是不是忘记给jar文件重命名了（run.sh里面有写）
> > > 
> > > 
> > > 也应该不是，我重命名成client.jar了。
> > 
> > 我两个月前打包过一个镜像，或许你可以去dockerhub看看... docker pull xiaoyangdkj/esurfingdialer:v1.4.0
> 
> 老哥创建容器的时候要写哪些参数，照着这个库里的 
> 这个运行吗？
> docker run -itd -e DIALER_USER=<用户名/手机号> -e DIALER_PASSWORD=<密码> --name dialer-client --network host --restart=always dialer
> 

README.MD里面有的......
![屏幕截图 2024-05-05 143003.png](https://github.com/Rsplwe/ESurfingDialer/assets/82305021/efffd4d2-f38c-40c7-828b-a20335595a96)

**Comment by wang8456** [comment]
> > > > > > > > 我的步骤是，先下载了jar，复制仓库的代码创建了run.sh文件，给了它们所有权限。然后通过dockerfile构建了镜像（其中把jar和sh文件copy进了docker），最后创建运行容器的时候报这个错误。
> > > > > > > > 完全是按着教程的步骤来，我不知道哪里出了错误，或者是什么原因导致问题。
> > > > > > > 
> > > > > > > 
> > > > > > > run.sh没有权限...或许你可以试试把文件复制到op软路由里面后再给权限 另外，教程里建议网络用host模式......
> > > > > > 
> > > > > > 
> > > > > > run.sh和jar文件我都给777权限了，网络也是host。你看我第二张和最后面那张图但是还是启动不了，会报403错误，一直重启。
> > > > > 
> > > > > 
> > > > > 我好像知道怎么回事了，你是不是忘记给jar文件重命名了（run.sh里面有写）
> > > > 
> > > > 
> > > > 也应该不是，我重命名成client.jar了。
> > > 
> > > 
> > > 我两个月前打包过一个镜像，或许你可以去dockerhub看看... docker pull xiaoyangdkj/esurfingdialer:v1.4.0
> > 
> > 
> > 老哥创建容器的时候要写哪些参数，照着这个库里的
> > 这个运行吗？
> > docker run -itd -e DIALER_USER=<用户名/手机号> -e DIALER_PASSWORD=<密码> --name dialer-client --network host --restart=always dialer
> 
> README.MD里面有的...... ![屏幕截图 2024-05-05 143003.png](https://private-user-images.githubusercontent.com/82305021/327994179-efffd4d2-f38c-40c7-828b-a20335595a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTE1NjMsIm5iZiI6MTcxNDg5MTI2MywicGF0aCI6Ii84MjMwNTAyMS8zMjc5OTQxNzktZWZmZmQ0ZDItZjM4Yy00MGM3LTgyOGItYTIwMzM1NTk1YTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDA2NDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYzJhMjA5MTNiMmZmZTZhNGI3MDU0NTUwZjkyMmFmODkxZTkzM2FiOTEyN2YxYTM2ZjcxYzc1MGM1ZjVlMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sw220Vw0I_evlNSC8ScQYRrc2yT0KSCZtlyHtVO1tjU)

好了谢谢老哥，呜呜我真不知道我哪里出错了，用你这个能行。我自己构建的就用不了。

**Comment by 250king** [comment]
其实我的做法是这样的：
参考自https://blog.kmtea.eu/p/221003-glibc-openwrt/，安装glibc；然后下载OpenJDK，解压后配置好PATH变量即可使用

**Comment by Rsplwe** [comment]
请检查所运行容器是否具有 glibc 核心库

**Comment by 250king** [comment]
其实我后来仔细研究了一番，发现其实网上也有不少现成的基于musl的JDK可以直接下载使用
https://www.azul.com/downloads/?os=alpine-linux&package=jdk#zulu
选好版本，解压后设置好环境变量就可以使用了
就不用必须安装glibc

**Comment by Rsplwe** [comment]
> 其实我后来仔细研究了一番，发现其实网上也有不少现成的基于musl的JDK可以直接下载使用 https://www.azul.com/downloads/?os=alpine-linux&package=jdk#zulu 选好版本，解压后设置好环境变量就可以使用了 就不用必须安装glibc

项目所使用的 native 库是基于glibc编译的，所以必须使用
