### ISSUE TITLE
请教问题：特定手机连接会掉网

### ISSUE THREAD

**Issue by liwinbq** [Rsplwe/ESurfingDialer#31]
![c5874f6a93c2a68953370817396a03a](https://github.com/Rsplwe/ESurfingDialer/assets/78959365/0ae0f203-e192-41f8-b9e6-6b10428d8eff)
学校是两台设备 如何顶出认证 在设备列表中看到小米6字眼

**Comment by 250king** [comment]
有个东西要提一下，去年11月天翼校园官方疑似发现了不区分设备来同时拨号的bug，然后就开始限制设备类型，也就是如果所在的学校是限死了一台手机+一台电脑，就不允许多一台手机同时在线
我尝试抓过电脑端的包，发现UA是不一样的，有可能两种客户端用的密钥也是不一样的（试过在这个脚本修改为电脑端的UA来登录，结果失败告终）
之前我原本开两个OpenWrt+这个脚本一起拨号，结果发现会踢一个下线

**Comment by Rsplwe** [comment]
fixed

**Comment by 250king** [comment]
https://github.com/Rsplwe/ESurfingDialer/issues/10
