### ISSUE TITLE
作者大大有没有想做一下注销登录的想法，之前一些开源项目的注销登录程序还能用

### ISSUE THREAD

**Issue by PC12138-Z** [Rsplwe/ESurfingDialer#34]
例如这个 https://github.com/Z446C/ESC-Z 。我现在openwrt的docker容器用你的脚本登录，注销用这个项目的https://github.com/Z446C/ESC-Z

**Comment by xiaoyangdkj** [comment]
其实你在电脑上用的时候，用Control+C退出jar就会自动退出登录了。(相应的,在docker中stop容器进程就行了)

**Comment by PC12138-Z** [comment]
但是退出jar或者停止掉容器后，还会保持在线一段时间。我提这个想法是因为有时候在线时间长了，学校会断掉网络，类似于被拉黑几分钟，几分钟后就网好了，但是这期间程序判定我网是通的，程序重启后也是这样，我就想着退出再登陆，刷新一下设备状态

**Comment by Rsplwe** [comment]
当收到退出信号时，会自动发送注销请求

**Comment by xiaoyangdkj** [comment]
> 但是退出jar或者停止掉容器后，还会保持在线一段时间。我提这个想法是因为有时候在线时间长了，学校会断掉网络，类似于被拉黑几分钟，几分钟后就网好了，但是这期间程序判定我网是通的，程序重启后也是这样，我就想着退出再登陆，刷新一下设备状态

在线时间长并不会自动断开网络，jar程序会定期发送保活包，除非你的电脑设置了自动休眠，使jar的数据和状态被锁定到了硬盘里

**Comment by PC12138-Z** [comment]
> > 但是退出jar或者停止掉容器后，还会保持在线一段时间。我提这个想法是因为有时候在线时间长了，学校会断掉网络，类似于被拉黑几分钟，几分钟后就网好了，但是这期间程序判定我网是通的，程序重启后也是这样，我就想着退出再登陆，刷新一下设备状态
> 
> 在线时间长并不会自动断开网络，jar程序会定期发送保活包，除非你的电脑设置了自动休眠，使jar的数据和状态被锁定到了硬盘里

我知道程序会一直发包保活，但是彻底关闭后，因为发过包保活的原因，他一般还能在线2小时左右，时间长的话能在线两天，这个是我这边的情况（其中没用再打开过程序），所以我想这个程序关闭后是没有退出登录的，只会等他自己掉线，我这边在电脑跟软路由docker上运行都是这样。还有就是我这边有检测多设备，虽然我部署了防检测，但是还是有几率会检测到，然后“黑号”被限流几十kb，可能是程序ping得通外面所以判定没有掉线，实际上设备是上不了网的。我重启程序甚至设备还是这样，不会重新再登录 （wait network check...），设备还是在线的，所以我才想着登出再重新登录解除"黑号"

**Comment by xiaoyangdkj** [comment]
> 我知道程序会一直发包保活，但是彻底关闭后，因为发过包保活的原因，他一般还能在线2小时左右，时间长的话能在线两天，这个是我这边的情况（其中没用再打开过程序），所以我想这个程序关闭后是没有退出登录的，只会等他自己掉线，我这边在电脑跟软路由docker上运行都是这样。还有就是我这边有检测多设备，虽然我部署了防检测，但是还是有几率会检测到，然后“黑号”被限流几十kb，可能是程序ping得通外面所以判定没有掉线，实际上设备是上不了网的。我重启程序甚至设备还是这样，不会重新再登录 （wait network check...），设备还是在线的，所以我才想着登出再重新登录解除"黑号"

你可以这样登出，手机连接校园网，然后在天翼客户端内"设备管理"中“下线 Xiaomi 6”
另外，openwrt应该没有装"mwan3"和"open猫猫-fake-ip"之类的吧

**Comment by PC12138-Z** [comment]
> > 我知道程序会一直发包保活，但是彻底关闭后，因为发过包保活的原因，他一般还能在线2小时左右，时间长的话能在线两天，这个是我这边的情况（其中没用再打开过程序），所以我想这个程序关闭后是没有退出登录的，只会等他自己掉线，我这边在电脑跟软路由docker上运行都是这样。还有就是我这边有检测多设备，虽然我部署了防检测，但是还是有几率会检测到，然后“黑号”被限流几十kb，可能是程序ping得通外面所以判定没有掉线，实际上设备是上不了网的。我重启程序甚至设备还是这样，不会重新再登录 （wait network check...），设备还是在线的，所以我才想着登出再重新登录解除"黑号"
> 
> 你可以这样登出，手机连接校园网，然后在天翼客户端内"设备管理"中“下线 Xiaomi 6” 另外，openwrt应该没有装"mwan3"和"open猫猫-fake-ip"之类的吧

有装但是没开，可能是因为有防检测的原因，手机客户端大部分时间都不会显示这个“xiaomi 6”设备，只是偶尔会显示，一般情况只显示我的手机终端，openwrt上登出方法我已经有了，用你的程序登录，再用另一个项目在openwrt实现登出（https://github.com/Z446C/ESC-Z），虽然这个登录不能用了，但是他的注销登录还能用
