### ISSUE TITLE
关于断网问题

### ISSUE THREAD

**Issue by Pennages** [Rsplwe/ESurfingDialer#40]
运行环境：Android 6/Debian GNU/Linux 12 (bookworm) [running via Linx Deploy]
问题描述：每周六日随机一个时间，脚本崩溃
ps:貌似是服务器发起的操作（

附件为输出日志
[error.log](https://github.com/user-attachments/files/15821245/error.log)

**Comment by Rsplwe** [comment]
运营商发起的断网操作，无解

**Comment by EricZhou05** [comment]
曲线救国吧
https://github.com/EricZhou05/ESurfingDialerTutorial#%E8%BF%9B%E9%98%B6
