### ISSUE TITLE
连不上了，是不是被禁了？

### ISSUE THREAD

**Issue by Siriustoco** [Rsplwe/ESurfingDialer#49]
![屏幕截图 2024-09-04 134835](https://github.com/user-attachments/assets/d6523374-8332-4273-8366-6f14c605fbd0)

**Comment by Rsplwe** [comment]
请检查账号密码是否正确，以及有无欠费

**Comment by Siriustoco** [comment]
并无欠费，账号密码正确，官方客户端能正常登录。这个现象是在学校说要在账号前+“QY”之后出现的。还想请问这个是通过手机ua认证还是什么？因为我试过手机客户端连接校园网登录每次都需要接收手机验证码

**Comment by Pennages** [comment]
大概率是卡验证码了，貌似就你们可🐱这样吧

**Comment by SummonHIM** [comment]
手机登录现在多了一个验证码。搞得直接登陆失败。。。

**Comment by yukikiuy** [comment]
可🐱学子😭了

**Comment by SummonHIM** [comment]
auth.cgi的body是怎么解码的。我这里刚抓完

**Comment by Rsplwe** [comment]
> 并无欠费，账号密码正确，官方客户端能正常登录。这个现象是在学校说要在账号前+“QY”之后出现的。还想请问这个是通过手机ua认证还是什么？因为我试过手机客户端连接校园网登录每次都需要接收手机验证码

麻烦截图下提示输入手机验证码的页面

**Comment by Rsplwe** [comment]
> auth.cgi的body是怎么解码的。我这里刚抓完

@SummonHIM https://github.com/Rsplwe/ESurfingDialer/blob/715418a0dede0b0043ff98bd85a836b826d94e89/src/main/kotlin/com/rsplwe/esurfing/hook/Session.kt#L29

**Comment by Rsplwe** [comment]
> 我刚刚也用jshell尝试了这个。但是什么都没解出来。他那个id是algo id吗

需要先在构造函数传入 getTicket 获取的 内容传入，才能调用 Session 里的方法

**Comment by Rsplwe** [comment]
> 我是用抓包软件抓的ticket。ticket解码也是一样吗

会请求两次 ticket，需填入 algo id 为 0 时获取到的内容

**Comment by Rsplwe** [comment]
@SummonHIM 可以的话，麻烦清空应用数据，然后获取完整的抓包结果发送到我主页的邮箱

**Comment by SummonHIM** [comment]
> @SummonHIM 可以的话，麻烦清空应用数据，然后获取完整的抓包结果发送到我主页的邮箱

稍等。抓包需要哪些链接的数据。这个vpn可能会顶掉我的抓包

**Comment by Rsplwe** [comment]
> 稍等。抓包需要哪些链接的数据。这个vpn可能会顶掉我的抓包

该应用的全部数据，建议用tcpdump抓包

**Comment by SummonHIM** [comment]
> > 稍等。抓包需要哪些链接的数据。这个vpn可能会顶掉我的抓包
> 
> 该应用的全部数据，建议用tcpdump抓包

已发送

**Comment by Rsplwe** [comment]
@SummonHIM 抓包内容里没有需要的内容，麻烦重新清空应用数据，并从应用初始化开始抓包

**Comment by zjun122** [comment]
可🐱输麻了

**Comment by SummonHIM** [comment]
> @SummonHIM 抓包内容里没有需要的内容，麻烦重新清空应用数据，并从应用初始化开始抓包

已重新抓了一份

**Comment by Siriustoco** [comment]
再次用手机客户端连接，发现验证码是同一个

**Comment by Rsplwe** [comment]
fixed https://github.com/Rsplwe/ESurfingDialer/commit/ecc72a009e3a4f0f4a7875d38e85aa7a90148c8f
