### ISSUE TITLE
[bug] 登录后连通性测试报错

### ISSUE THREAD

**Issue by Pennages** [Rsplwe/ESurfingDialer#54]
登录后，如果有设备长时间占满所有网络时，会导致脚本崩溃错误，不会重新对服务器进行握手而导致断网（需要重新启动脚本）
![Screenshot_20240905-232638](https://github.com/user-attachments/assets/489d5322-289e-4e48-a8ab-8bca15e6465f)

具体两份不同时间段日志log已符上
[eslog_2490520_G.log](https://github.com/user-attachments/files/16901490/eslog_2490520_G.log)
[eslog_2490607_G.log](https://github.com/user-attachments/files/16901491/eslog_2490607_G.log)

**Comment by Rsplwe** [comment]
有尝试 1.6.0 版本吗

**Comment by Pennages** [comment]
> 有尝试 1.6.0 版本吗

刚刚更新了，然后给了一波网络压力，两个都报错，其中一个直接自行Shutting down了（我没有ctrlc或者killall）
另一个没有Shutting down，虽然报错了但目前还能正常进行握手。
两个是不同的账号，没有被限制使用

以下是被Shutting down的截图/日志
![Screenshot_20240906-182502](https://github.com/user-attachments/assets/4d2eb644-301c-4391-be82-3c0782a8e96d)
[eslog_24090618_vince.log](https://github.com/user-attachments/files/16906589/eslog_24090618_vince.log)

以下是没有Shutting down的截图/日志
![Screenshot_20240906-182539
[eslog_24090618_cp8675.log](https://github.com/user-attachments/files/16906628/eslog_24090618_cp8675.log)
](https://github.com/user-attachments/assets/f7f2e7d6-e4d3-4b65-b362-b3f3b4ede90f)

**Comment by Rsplwe** [comment]
对于连通性测试，可以尝试在 hosts 文件里固定 connect.rom.miui.com 的 ip，但是由于网络异常导致心跳包无法发送本身是无解的。

**Comment by Pennages** [comment]
> > > 对于连通性测试，可以尝试在 hosts 文件里固定 connect.rom.miui.com 的 ip，但是由于网络异常导致心跳包无法发送本身是无解的。
> > 
> > 
> > 也就是说，心跳包发送失败时不会尝试重新发送，而需要等待下一个周期才会重新发送么
> 
> 因为在心跳包无法发送的情况下，网络本身已经断掉了

好的非常感谢
