### ISSUE TITLE
欲研究模拟电脑端登录

### ISSUE THREAD

**Issue by 250king** [Rsplwe/ESurfingDialer#60]
自从去年11月开始，校园网已经不允许两台手机同时登录，具体体现在开两台机子分别登录，结果出现一台被踢下线
我在预想是否通过修改UA为电脑端的UA就可以实现模拟电脑端登录？

**Comment by 250king** [comment]
不关路由器吧？和你客户端的ua有关吧（不出意外密钥应该也是不一样的）

**Comment by liu2-3zhi** [comment]
或许可以看看


https://github.com/Rsplwe/ESurfingDialer/blob/028baad7f93dfce1748c08be205421ffbed38e24/src/main/kotlin/com/rsplwe/esurfing/Constants.kt#L10

**Comment by liu2-3zhi** [comment]
我查看了其它项目的User-Agent，发现和本项目不一样。或许修改User-Agent囧能模拟电脑登陆

https://github.com/Pandaft/ESurfingPy-CLI/blob/9a4ba18a54962208a241e258eca5262caa4535d8/esurfingpy/esurfing.py#L305

**Comment by liu2-3zhi** [comment]
经过多次抓包，发现电脑的UA是
`const val USER_AGENT = "CCTP/WinSVR5/1066"`

**Comment by liu2-3zhi** [comment]
或许，还需要改一下设备名

https://github.com/Rsplwe/ESurfingDialer/blob/028baad7f93dfce1748c08be205421ffbed38e24/src/main/kotlin/com/rsplwe/esurfing/Constants.kt#L14

**Comment by liu2-3zhi** [comment]
经过测试，发现只修改ua和host name无法实现电脑端认证

**Comment by 250king** [comment]
是这样的，我之前试过直接改，两者用的key肯定是不一样，但是它们用的endpoint应该是一样的，我试过抓包。
这个应该是要想办法反编译客户端

**Comment by Rsplwe** [comment]
加解密部分依赖于验证时动态下发的原生库，所以无法简单的通过更改UA来切换

**Comment by 250king** [comment]
之前试着反编译，里面有一堆sub_function，混淆过了，根本玩不了一点
我也不太懂Windows应用反编译

**Comment by liu2-3zhi** [comment]
我尝试抓包获取了电脑端登陆时候所需要的参数。
` const val PORTAL_END_TAG = "//config.campus.js.chinatelecom.com-->"
    const val PORTAL_START_TAG = "<!--//config.campus.js.chinatelecom.com"
	 const val REQUEST_ACCEPT = "text/html,text/xml,application/xhtml+xml,application/x-javascript,*/*"
	 const val USER_AGENT = "CCTP/WinSVR5/1066"`

**Comment by liu2-3zhi** [comment]
但是确实跟换后无法使用

**Comment by liu2-3zhi** [comment]
或许就是加密解密的问题

**Comment by 250king** [comment]
想过用hook的方法，目前为止我就知道把ESurfingClient.exe给suspend后还能保持上网，那是因为ESurfingSrv.exe在后台依旧发包
可以参考我这一个项目https://github.com/250king/ESurfingAutoLogin
说明可能在某个逻辑上面这两个是分开的，就可以专注某一个地方去分析

**Comment by Rsplwe** [comment]
我觉得需要稍微解释一下，首先，本项目的原理是通过 unidbg 来调用加载验证时动态下发的原生库，这个为平台和CPU架构强相关，无法替代

**Comment by liu2-3zhi** [comment]
那是不是可以替换环境成X86来实现？

**Comment by Rsplwe** [comment]
> 那是不是可以替换环境成X86来实现？

原理上行不通，unidbg 只适用于模拟 Android 环境

**Comment by liu2-3zhi** [comment]
直接运行？本身就是X86架构呢

**Comment by liu2-3zhi** [comment]
不知道行不行？需要提供抓到数据不？

**Comment by 250king** [comment]
主要是Windows是用什么dll，已经怎么调用，所以就不知道怎么hook

**Comment by liu2-3zhi** [comment]
我试了一下，发现客户端可以被debug


x64dbg可以用
https://x64dbg.com/

**Comment by liu2-3zhi** [comment]
不知道Linux版本的天翼校园网客户端是不是用的是电脑版本的UA

http://zsteduapp.10000.gd.cn/More/linuxDownLoad/linuxDownLoad.html

**Comment by 250king** [comment]
应该是吧，不过Linux也是头一次听说

**Comment by liu2-3zhi** [comment]
UA是CCTP/LinuxIpv664

**Comment by 250king** [comment]
你是广东区域吗？我没听说过Linux版本，在网页版本也没有这个玩意

**Comment by liu2-3zhi** [comment]
我是广东这边的

**Comment by liu2-3zhi** [comment]
你可以测试运行Linux版本能不能用吗？我这边不是很方便测试，因为有人在打游戏，我怕挤掉了Openwrt上的认证程序

**Comment by 250king** [comment]
我到时候试一试吧，不过我觉得应该是不给用的
其实MacOS端也可以看一看，如果基于Swift估计就简单点了

**Comment by liu2-3zhi** [comment]
经过测试，Linux版本可以正常使用，且不会挤掉手机

**Comment by liu2-3zhi** [comment]
![image](https://github.com/user-attachments/assets/d3ed4b28-3f48-4936-a94d-d1947bd7bdb5)

**Comment by liu2-3zhi** [comment]
好家伙，注销功能用不了

**Comment by liu2-3zhi** [comment]
https://github.com/liu23zhi/ESurfingDialerDocker/

我尝试构建了一个docker镜像，不知道行不行。
