### ISSUE TITLE
新动态库无法使用，换回旧版正常

### ISSUE THREAD

**Issue by ayanami-desu** [Rsplwe/ESurfingDialer#64]
dialer-client  | Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long com.github.unidbg.arm.backend.dynarmic.Dynarmic.nativeInitialize(boolean)'
dialer-client  | 	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.nativeInitialize(Native Method)
dialer-client  | 	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.<init>(Dynarmic.java:51)
dialer-client  | 	at com.github.unidbg.arm.backend.DynarmicFactory.newBackendInternal(DynarmicFactory.java:25)
dialer-client  | 	at com.github.unidbg.arm.backend.BackendFactory.newBackend(BackendFactory.java:17)
dialer-client  | 	at com.github.unidbg.arm.backend.BackendFactory.createBackend(BackendFactory.java:32)
dialer-client  | 	at com.github.unidbg.AbstractEmulator.<init>(AbstractEmulator.java:98)
dialer-client  | 	at com.github.unidbg.arm.AbstractARM64Emulator.<init>(AbstractARM64Emulator.java:59)
dialer-client  | 	at com.github.unidbg.linux.android.AndroidARM64Emulator.<init>(AndroidARM64Emulator.java:33)
dialer-client  | 	at com.github.unidbg.linux.android.AndroidEmulatorBuilder.build(AndroidEmulatorBuilder.java:22)
dialer-client  | 	at com.github.unidbg.linux.android.AndroidEmulatorBuilder.build(AndroidEmulatorBuilder.java:6)
dialer-client  | 	at com.rsplwe.esurfing.hook.AndroidMock.<init>(AndroidMock.kt:22)
dialer-client  | 	at com.rsplwe.esurfing.hook.Session.<init>(Session.kt:21)
dialer-client  | 	at com.rsplwe.esurfing.Client.initSession(Client.kt:104)
dialer-client  | 	at com.rsplwe.esurfing.Client.authorization(Client.kt:60)
dialer-client  | 	at com.rsplwe.esurfing.Client.run(Client.kt:48)
dialer-client  | 	at com.rsplwe.esurfing.DialerApp.main(DialerApp.kt:63)
dialer-client  | Shutting down...
dialer-client exited with code 1

**Comment by Rsplwe** [comment]
arm?

**Comment by ayanami-desu** [comment]
> arm?

是linux_arm64，其他两个未知

**Comment by Rsplwe** [comment]
系统环境是？

**Comment by ayanami-desu** [comment]
> 系统环境是？

[hs_err_pid8.log](https://github.com/user-attachments/files/17002696/hs_err_pid8.log)
可以看这个

**Comment by ayanami-desu** [comment]
另外问一下，readme中说运行时要加-d，但我实践下来去掉-d才能正常运行。

**Comment by Rsplwe** [comment]
> > 系统环境是？
> 
> [hs_err_pid8.log](https://github.com/user-attachments/files/17002696/hs_err_pid8.log) 可以看这个

提供下设备型号、系统环境、以及是不是跑在docker里

**Comment by ayanami-desu** [comment]
斐讯n1, openwrt, 内核6.1.109，在docker中运行

**Comment by PC12138-Z** [comment]
> 斐讯n1, openwrt, 内核6.1.109，在docker中运行

我也是N1，也是在docker里面运行，目前为止没出现你那样的问题

**Comment by Rsplwe** [comment]
麻烦尝试下更新后的库 https://github.com/Rsplwe/ESurfingDialer/commit/028baad7f93dfce1748c08be205421ffbed38e24

**Comment by ayanami-desu** [comment]
已经正常
