### ISSUE TITLE
最新版run.sh参数错误

### ISSUE THREAD

**Issue by EricZhou05** [Rsplwe/ESurfingDialer#66]
[ESurfingDialer v1.7.0](https://github.com/Rsplwe/ESurfingDialer/releases/tag/v1.7.0)
OpenWrt使用最新版构建docker，容器报参数错误
```
[12:49:51 184] ERROR [com.rsplwe.esurfing.DialerApp] (DialerApp:46) - Unrecognized option: -d
usage: ESurfingDialer
 -p,--password <password>   Login User Password
 -s,--sms <sms>             Pre-enter verification code
 -u,--user <user>           Login User (Phone Number or Other)
```

之后排查源于 **run.sh** 末尾有 **-d** 参数

旧版本没有此问题，**run.sh**是否不再需要输入该参数？

个人问题：宿舍百兆宽带入门x86_64架构软路由双网口有什么型号推荐呀~

**Comment by Rsplwe** [comment]
新版去掉了 -d 参数
