### ISSUE TITLE
在网速跑满的情况下，很大几率会出现检查网络连通性失败，发不出心跳包

### ISSUE THREAD

**Issue by PC12138-Z** [Rsplwe/ESurfingDialer#68]
![屏幕截图 2024-10-03 175301](https://github.com/user-attachments/assets/dfadd263-729e-4128-8b7e-9c0fd98b7422)

**Comment by liu2-3zhi** [comment]
@PC12138-Z 我查看你的相关issue，请不要使用ua修改的相关插件，使用双层openwrt

**Comment by PC12138-Z** [comment]
> @PC12138-Z 我查看你的相关issue，请不要使用ua修改的相关插件，使用双层openwrt

我知道ua修改会导致登录不上去，我就是电脑接路由器，其他什么都没弄，现在问题我已经找到了，学校检测到共享网络，给频繁断网了，解决方法我也找到了

**Comment by liu2-3zhi** [comment]
> > @PC12138-Z 我查看你的相关issue，请不要使用ua修改的相关插件，使用双层openwrt
> 
> 我知道ua修改会导致登录不上去，我就是电脑接路由器，其他什么都没弄，现在问题我已经找到了，学校检测到共享网络，给频繁断网了，解决方法我也找到了

你打算怎么解决？？？

**Comment by PC12138-Z** [comment]
> > > @PC12138-Z 我查看你的相关issue，请不要使用ua修改的相关插件，使用双层openwrt
> > 
> > 
> > 我知道ua修改会导致登录不上去，我就是电脑接路由器，其他什么都没弄，现在问题我已经找到了，学校检测到共享网络，给频繁断网了，解决方法我也找到了
> 
> 你打算怎么解决？？？使用UA2F？？？

不管是ua2f，还是ua3f，用了都登录不上去，不用就会被检测，只能老老实实用电脑双网口共享

**Comment by liu2-3zhi** [comment]
> > > > @PC12138-Z 我查看你的相关issue，请不要使用ua修改的相关插件，使用双层openwrt
> > > 
> > > 
> > > 我知道ua修改会导致登录不上去，我就是电脑接路由器，其他什么都没弄，现在问题我已经找到了，学校检测到共享网络，给频繁断网了，解决方法我也找到了
> > 
> > 
> > 你打算怎么解决？？？使用UA2F？？？
> 
> 不管是ua2f，还是ua3f，用了都登录不上去，不用就会被检测，只能老老实实用电脑双网口共享

我还以为啥办法。我这边使用我那个Docker镜像就行，啥检测都没有。

**Comment by PC12138-Z** [comment]
> > > > > @PC12138-Z 我查看你的相关issue，请不要使用ua修改的相关插件，使用双层openwrt
> > > > 
> > > > 
> > > > 我知道ua修改会导致登录不上去，我就是电脑接路由器，其他什么都没弄，现在问题我已经找到了，学校检测到共享网络，给频繁断网了，解决方法我也找到了
> > > 
> > > 
> > > 你打算怎么解决？？？使用UA2F？？？
> > 
> > 
> > 不管是ua2f，还是ua3f，用了都登录不上去，不用就会被检测，只能老老实实用电脑双网口共享
> 
> 我还以为啥办法。我这边使用我那个Docker镜像就行，啥检测都没有。

用ua2f的话，还是有办法的，不过稍微有点不稳定，还在测试

**Comment by liu2-3zhi** [comment]
套一层ua3f就好了，只是我这边目前不检测，就直接去掉了

**Comment by PC12138-Z** [comment]
> 套一层ua3f就好了，只是我这边目前不检测，就直接去掉了。对了，还有ttl，记得改一下防火墙

你用了ua3f还能登录上去？
我是套了ua3f是登录不上去，登录的ua是会被拦截，就算先登录再开ua3f，心跳包也发不出去

**Comment by liu2-3zhi** [comment]
![image](https://github.com/user-attachments/assets/7141964d-8ec0-4de3-9390-82259806e1c9)
有没有可能我开了很多个OpenWrt，OpenWrt2用来登录，OpenWrt3用来解决UA

**Comment by PC12138-Z** [comment]
> ![image](https://private-user-images.githubusercontent.com/43312573/373949548-b44f953d-7a94-4123-bfab-be54668f4586.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjA4OTQsIm5iZiI6MTcyODIyMDU5NCwicGF0aCI6Ii80MzMxMjU3My8zNzM5NDk1NDgtYjQ0Zjk1M2QtN2E5NC00MTIzLWJmYWItYmU1NDY2OGY0NTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEzMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTJkNTUzMjM4MzRhOWZlNDJhYTI3NTE0NDViZTFiZGZiNWI1NzBkYzdhYWZkOGI3ZGM5MDcxYmYxYWRhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sbhZtJahC37xfuNq_0oj99tE1x9Ntibz6GBP7l0pd5w)
> 
> 有没有可能我开了很多个OpenWrt，OpenWrt2用来登录，OpenWrt3用来解决UA
我开了两个，一个负责登录，另一个负责处理ua，但是没什么用，还是会被检测到，就挺无语，之前还挺有效果的

**Comment by liu2-3zhi** [comment]
是不是你没有改ttl导致的?

**Comment by PC12138-Z** [comment]
> 是不是你没有改ttl导致的?

改了，不管了，现在凑合用着吧
