### ISSUE TITLE
jar不定期崩溃

### ISSUE THREAD

**Issue by BadGhost520** [Rsplwe/ESurfingDialer#81]
jar程序崩溃，时间不定，附上程序运行log和三个不同时间的崩溃logs，最新编译的jar
[dialer.log](https://github.com/user-attachments/files/18113523/dialer.log)
[hs_err_pid7.log](https://github.com/user-attachments/files/18113525/hs_err_pid7.log)
[hs_err_pid9.log](https://github.com/user-attachments/files/18113526/hs_err_pid9.log)
[hs_err_pid8.log](https://github.com/user-attachments/files/18113528/hs_err_pid8.log)

**Comment by Rsplwe** [comment]
尝试下这个构建，应该能解决问题

https://github.com/Rsplwe/ESurfingDialer/actions/runs/12468003026/artifacts/2356084355

**Comment by BadGhost520** [comment]
> 尝试下这个构建，应该能解决问题
> 
> https://github.com/Rsplwe/ESurfingDialer/actions/runs/12468003026/artifacts/2356084355

我试运行几天看看，之前那个用jdk21的版本的jar也是蛮稳定的，会崩溃的是之前最新的jdk23的版本的代码构建出来的jar

**Comment by Rsplwe** [comment]
> > 尝试下这个构建，应该能解决问题
> > https://github.com/Rsplwe/ESurfingDialer/actions/runs/12468003026/artifacts/2356084355
> 
> 我试运行几天看看，之前那个用jdk21的版本的jar也是蛮稳定的，会崩溃的是之前最新的jdk23的版本的代码构建出来的jar

理论上来说，跟jvm版本无关

**Comment by BadGhost520** [comment]
忘了关闭了，最新版本构建很稳定，甚至把每天固定十五小时断网的故障跟着修复了
